[package]
name = "miu-com"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
socketcan = "1.7.0"
deku = "0.13.0"
eframe = "0.18.0"
interfaces = "0.0.8"
